#include<iostream>
#include<string>
using namespace std;


int main()
{
	int score = 0;
	cout << "请给电影打分：" << endl;
	cin >> score;

	cout << "你输入的分数为：" << score << endl;
	
	switch (score)
	{
	case 10:
		cout << "经典电影" << endl;
		break;
	case 9:
		cout << "经典电影" << endl;
		break;
	case 8:
		cout << "好电影" << endl;
		break;
	case 7:
		cout << "好电影" << endl;
		break;
	case 6:
		cout << "一般" << endl;
		break;
	default:
		cout << "烂片" << endl;
		break;


	}



	system("pause");
	return 0;
}
