switch语句
#include<iostream>
#include<string>
using namespace std;


int main()
{
	int score = 0;
	cout << "请给电影打分：" << endl;
	cin >> score;

	cout << "你输入的分数为：" << score << endl;
	
	switch (score)
	{
	case 10:
		cout << "经典电影" << endl;
		break;
	case 9:
		cout << "经典电影" << endl;
		break;
	case 8:
		cout << "好电影" << endl;
		break;
	case 7:
		cout << "好电影" << endl;
		break;
	case 6:
		cout << "一般" << endl;
		break;
	default:
		cout << "烂片" << endl;
		break;


	}



	system("pause");
	return 0;
}


while语句
int main()
{
	int num = 0;
	while (num < 10)
	{
		cout << num << endl;
		num++;
	}
	system("pause");
	return 0;
}



猜数字小游戏
#include<iostream>
#include<string>
using namespace std;
#include<ctime>

int main()
{
	//添加随机数种子作用利用当前系统时间生成随机数，
	// 防止每次随机数都一样
	
	srand((unsigned int)time(NULL));

	//生成1-100的随机数
	int num = rand() % 100 + 1;//rand生成0到99 所以后面加1
	//cout << num << endl;
	int grass = 0;
	while (1)
	{
		cin >> grass;
		if (grass > num)
		{
			cout << "猜测过大" << endl;
		}
		else if (grass < num)
		{
			cout << "猜测过小" << endl;
		}
		else
		{
			cout << "猜对啦" << endl;
			break;
		}
	}

	system("pause");
	return 0;
}


水仙花
#include<iostream>
#include<string>
using namespace std;
#include<ctime>

int main()
{
	int num = 100;
	do
	{
		int a = 0;
	    int b = 0;
	    int c = 0;

		a = num % 10;//个位
		b = num / 10 % 10;//十位
		c = num / 100;//百位

		if(a*a*a+b*b*b+ c*c*c == num)
		{
		cout << num << endl;
		}
		num++;
	}
	while(num < 1000);



	system("pause");
	return 0;
}
